    - name: Get Clock Information
      ansible.builtin.set_fact:
        dev_clock: "{{ ios_vars.stdout_lines[0][0] }}"
      when: ansible_network_os == 'cisco.ios.ios'

    - name: Get Clock Information
      ansible.builtin.set_fact:
        dev_ntp: "{{ ios_vars.stdout_lines[1] | join('\n') }}"
      when:
        - ios_vars.stdout[1] is defined
        - ansible_network_os == 'cisco.ios.ios'

    - name: Get Clock Information
      ansible.builtin.set_fact:
        dev_ntp: "NTP Not Configured"
      when:
        - ios_vars.stdout[1] is not defined
        - ansible_network_os == 'cisco.ios.ios'
