    - name: Get Clock Information
      ansible.builtin.set_fact:
        dev_clock: "{{ asa_vars.stdout_lines[0][0] }}"
      when: ansible_network_os == 'cisco.asa.asa'

    - name: Get Clock Information
      ansible.builtin.set_fact:
        dev_ntp: "{{ asa_vars.stdout_lines[1] | join('\n') }}"
      when:
        - asa_vars.stdout[1] is defined
        - ansible_network_os == 'cisco.asa.asa'

    - name: Get Clock Information
      ansible.builtin.set_fact:
        dev_ntp: "NTP Not Configured"
      when:
        - asa_vars.stdout[1] is not defined
        - ansible_network_os == 'cisco.asa.asa'
