---
##HASHING
#SHA 1 
- name: compensate for inconsistent naming
  set_fact:
    p2_hash_algo: "esp-sha-hmac"
  when: ike_version == "1" and hash_algo.lower() == "sha-1"
- name: compensate for inconsistent naming
  set_fact:
    p2_hash_algo: "esp-sha-hmac"
  when: ike_version == "1" and hash_algo.lower() == "sha"
- name: compensate for inconsistent naming
  set_fact:
    p2_hash_algo: "sha-1"
  when: ike_version == "2" and hash_algo.lower() == "sha"
- name: compensate for inconsistent naming
  set_fact:
    p2_hash_algo: "sha-1"
  when: ike_version == "2" and hash_algo.lower() == "sha-1"
  #P2 Specific Hash Algos, I still need to pass the variables
- name: compensate for inconsistent naming
  set_fact:
    p2_hash_algo: "sha-256"
  when: ike_version == "2" and hash_algo.lower() == "sha-256"
- name: compensate for inconsistent naming
  set_fact:
    p2_hash_algo: "sha-384"
  when: ike_version == "2" and hash_algo.lower() == "sha-384"
- name: compensate for inconsistent naming
  set_fact:
    p2_hash_algo: "sha-512"
  when: ike_version == "2" and hash_algo.lower() == "sha-512"
#that's it for hashing, IKEv2 is sensible about this, but I need to change the variable in that case and add failure conditions for wrong configurations
- name: "Fail job if Impossible Configuration"
  fail:
    msg: "IKEv1 only allows sha-1 and md5 hashing"
  when: ike_version == "1" and hash_algo.lower() != "sha-1" and hash_algo.lower() != "sha" and hash_algo.lower() != "md5"
- name: "My pride prevents me from using md5"
  fail:
    msg: "Use modern hashing algorithms, I don't care what the customer says"
  when: hash_algo.lower() == "md5"


##ENCRYPTION
#IKEv1 nonsense
- name: compensate for inconsistent naming
  set_fact:
    p2_encrypt_algo: "esp-aes-256"
  when: ike_version == "1" and encrypt_algo.lower() == "aes-256"
#IKEv2 Chaddery
- name: compensate for inconsistent naming
  set_fact:
    p2_encrypt_algo: "aes-256"
  when: ike_version == "2" and encrypt_algo.lower() == "aes-256"
#Insta-Failure
- name: "Your waifu is trash"
  fail:
    msg: "Use modern Encryption algorithms, I don't care what the customer says"
  when: encrypt_algo.lower() == "des"
- name: "Your waifu is trash"
  fail:
    msg: "Use modern Encryption algorithms, I don't care what the customer says"
  when: encrypt_algo.lower() == "3des"
- name: "Your waifu is trash"
  fail:
    msg: "Use modern Encryption algorithms, I don't care what the customer says"
  when: encrypt_algo.lower() == "aes-192"
- name: "Your waifu is trash"
  fail:
    msg: "Use modern Encryption algorithms, I don't care what the customer says"
  when: encrypt_algo.lower() == "aes"
